services:
  lubw-client:
    image: ghcr.io/urban-air-lab/lubw_client:latest
    container_name: lubw-client
    restart: always
    environment:
      - LUBW_USERNAME=${LUBW_USERNAME}
      - LUBW_PASSWORD=${LUBW_PASSWORD}
      - LUBW_BASE_URL=${LUBW_BASE_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_SERVER=${MQTT_SERVER}
      - MQTT_PORT=${MQTT_PORT}
    networks:
      - iot
    depends_on:
      - mosquitto
      - influxdb

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    expose:
      - "8883"
      - "9001"
    networks:
      - iot
      - frontend
    volumes:
      - ./configs/mosquitto/:/mosquitto/config/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      # TCP router for MQTT over TLS
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.${TRAEFIK_DOMAIN}`)"
      - "traefik.tcp.routers.mqtt.entrypoints=mqttsecure"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=8883"
      - "traefik.tcp.routers.mqtt.tls.certresolver=myresolver"

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    networks:
      - iot
      - frontend
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
      - ./scripts/init-influx.sh:/docker-entrypoint-initdb.d/init-influx.sh
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=urban-air-lab
      - DOCKER_INFLUXDB_INIT_BUCKET=test-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      - "traefik.http.routers.influx.rule=Host(`influx.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.influx.entrypoints=web"

      - "traefik.http.routers.influx-secure.rule=Host(`influx.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.influx-secure.entrypoints=websecure"
      - "traefik.http.routers.influx-secure.tls=true"
      - "traefik.http.routers.influx-secure.tls.certresolver=myresolver"

  telegraf:
    image: telegraf
    container_name: telegraf
    hostname: telegraf
    restart: always
    networks:
      - iot
      - frontend
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    depends_on:
      - mosquitto
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    networks:
      - iot
      - frontend
    volumes:
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      - "traefik.http.routers.grafana.rule=Host(`grafana.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"

      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=myresolver"

networks:
  iot:
  frontend:

volumes:
  grafana-data:
  influxdb-data:
  influxdb-config: