services:
  traefik:
    image: traefik:3.5
    command:
      --api.insecure=false 
      --providers.docker=true
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

networks:
  frontend:

