services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring
    command: "--path.rootfs=/host"
    pid: host
    volumes:
      - /:/host:ro,rslave
    labels:
      - "traefik.enable=false"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    labels:
      - "traefik.enable=false"

  prometheus:
    image: docker.io/prom/prometheus:v3.6.0
    container_name: prometheus
    restart: always
    networks:
      - monitoring
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    ports:
      - "9090:9090"
    volumes:
      - /opt/ual/configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ual_infrastructure_deployments_frontend"

      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.prometheus.entrypoints=web"

      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.prometheus-secure.entrypoints=websecure"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.tls.certresolver=myresolver"

  grafana:
    image: grafana/grafana:12.3.2-security-01-ubuntu
    container_name: grafana
    restart: always
    networks:
      - iot
      - frontend
      - monitoring
    volumes:
      - /opt/ual/configs/grafana-provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ual_infrastructure_deployments_frontend"

      - "traefik.http.routers.grafana.rule=Host(`grafana.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"

      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=myresolver"

networks:
  iot:
  frontend:
  monitoring:

volumes:
  grafana-data:
  prometheus-data: