name: "Deploy Inference Server"

on:
  workflow_dispatch:

jobs:
  deploy-inference-server:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Deploy Inference Server
        env:
          MQTT_USERNAME: "${{ secrets.MQTT_USERNAME }}"
          MQTT_PASSWORD: "${{ secrets.MQTT_PASSWORD }}"
          MQTT_SERVER: "${{ secrets.MQTT_SERVER }}"
          MQTT_PORT: "${{ secrets.MQTT_PORT }}"

          INFLUX_URL: "${{ secrets.INFLUX_URL }}"
          INFLUX_ORG: "${{ secrets.INFLUX_ORG }}"

          DOCKER_INFLUXDB_INIT_USERNAME: "${{ secrets.DOCKER_INFLUXDB_INIT_USERNAME }}"
          DOCKER_INFLUXDB_INIT_PASSWORD: "${{ secrets.DOCKER_INFLUXDB_INIT_PASSWORD }}"
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${{ secrets.DOCKER_INFLUXDB_INIT_ADMIN_TOKEN }}"

          MLFLOW_URL: "${{ secrets.MLFLOW_URL }}"
          MLFLOW_FLASK_SERVER_SECRET_KEY: "${{ secrets.MLFLOW_FLASK_SERVER_SECRET_KEY }}"
          MLFLOW_USERNAME: "${{ secrets.MLFLOW_USERNAME }}"
          MLFLOW_PASSWORD: "${{ secrets.MLFLOW_PASSWORD }}"
        run: |
          docker -H ssh://root@urbanairlab.hn compose -p ual_infrastructure_deployments -f docker-compose-inference.yaml rm -f -s -v
          docker -H ssh://root@urbanairlab.hn compose -p ual_infrastructure_deployments -f docker-compose-inference.yaml up -d --pull always
          
          
